package com.khiar.pembuatstiker;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.net.Uri;import android.provider.MediaStore;import android.view.*;import android.widget.*;import java.io.*;

public class MainActivity extends Activity {
 LinearLayout root; ImageView preview; Uri selected; Bitmap edited; String text="";
 public void onCreate(Bundle b){super.onCreate(b); build();}
 TextView title(String s){TextView t=new TextView(this);t.setText(s);t.setTextSize(22);t.setPadding(16,20,16,12);return t;}
 void build(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(16,16,16,16);root.addView(title("Pembuat Stiker WhatsApp"));
  Button add=new Button(this);add.setText("＋ Tambah Foto");root.addView(add);preview=new ImageView(this);preview.setAdjustViewBounds(true);preview.setScaleType(ImageView.ScaleType.CENTER_INSIDE);root.addView(preview,new LinearLayout.LayoutParams(-1,0,1));
  Button direct=new Button(this);direct.setText("Langsung Jadi Stiker");root.addView(direct);Button edit=new Button(this);edit.setText("Edit");root.addView(edit);Button wa=new Button(this);wa.setText("Simpan ke WhatsApp");root.addView(wa);setContentView(root);
  add.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,10);});
  direct.setOnClickListener(v->{if(selected==null) toast("Pilih foto dulu."); else {edited=makeSticker(false);toast("Stiker siap.");}});
  edit.setOnClickListener(v->{if(selected==null){toast("Pilih foto dulu.");return;} editDialog();});
  wa.setOnClickListener(v->{if(selected==null){toast("Pilih foto dulu.");return;} if(edited==null)edited=makeSticker(false); addToWhatsApp();});
 }
 void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
 protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==10&&c==RESULT_OK&&d!=null){selected=d.getData();try{getContentResolver().takePersistableUriPermission(selected,d.getFlags()&Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception e){} preview.setImageURI(selected);edited=null;}}
 void editDialog(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(24,0,24,0);EditText e=new EditText(this);e.setHint("Teks stiker (opsional)");box.addView(e);Button bg=new Button(this);bg.setText("Hapus background sederhana");box.addView(bg);final boolean[] remove={false};bg.setOnClickListener(v->{remove[0]=true;bg.setText("Background akan dihapus");});new AlertDialog.Builder(this).setTitle("Edit stiker").setView(box).setPositiveButton("Simpan",(d,w)->{text=e.getText().toString();edited=makeSticker(remove[0]);preview.setImageBitmap(edited);toast("Edit disimpan.");}).setNegativeButton("Batal",null).show();}
 Bitmap makeSticker(boolean remove){try{Bitmap src=MediaStore.Images.Media.getBitmap(getContentResolver(),selected);int max=512;float scale=Math.min(1f,Math.min(max/(float)src.getWidth(),max/(float)src.getHeight()));Bitmap b=Bitmap.createScaledBitmap(src,Math.max(1,(int)(src.getWidth()*scale)),Math.max(1,(int)(src.getHeight()*scale)),true);Bitmap out=Bitmap.createBitmap(512,512,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(out);c.drawColor(Color.TRANSPARENT,PorterDuff.Mode.CLEAR);float x=(512-b.getWidth())/2f,y=(512-b.getHeight())/2f;c.drawBitmap(b,x,y,null);if(remove){int w=out.getWidth(),h=out.getHeight();int edge=out.getPixel(w/2,0);int er=Color.red(edge),eg=Color.green(edge),eb=Color.blue(edge);for(int yy=0;yy<h;yy++)for(int xx=0;xx<w;xx++){int p=out.getPixel(xx,yy);if(Math.abs(Color.red(p)-er)<25&&Math.abs(Color.green(p)-eg)<25&&Math.abs(Color.blue(p)-eb)<25)out.setPixel(xx,yy,Color.TRANSPARENT);}}if(!text.isEmpty()){Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);p.setColor(Color.WHITE);p.setTextSize(52);p.setTextAlign(Paint.Align.CENTER);p.setStyle(Paint.Style.FILL);p.setShadowLayer(8,2,2,Color.BLACK);c.drawText(text,256,480,p);}return out;}catch(Exception e){toast("Gagal memproses foto.");return null;}}
 void addToWhatsApp(){try{File dir=new File(getFilesDir(),"stickers");dir.mkdirs();for(File f:dir.listFiles()!=null?dir.listFiles():new File[0])f.delete();File f=new File(dir,"sticker_1.webp");FileOutputStream os=new FileOutputStream(f);edited.compress(Bitmap.CompressFormat.WEBP,90,os);os.close();Intent i=new Intent("com.whatsapp.intent.action.ENABLE_STICKER_PACK");i.putExtra("sticker_pack_id","khiar_pack");i.putExtra("sticker_pack_authority",StickerProvider.AUTH);i.putExtra("sticker_pack_name","Stiker Saya");startActivity(i);}catch(Exception e){toast("WhatsApp belum mendukung penambahan paket dari aplikasi ini atau WhatsApp tidak terpasang.");}}
}
