package com.khiar.pembuatstiker;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.net.Uri;import android.provider.MediaStore;import android.view.*;import android.widget.*;import java.io.*;import java.util.*;

public class MainActivity extends Activity {
 LinearLayout root; ImageView preview; Uri selected; Bitmap edited; ArrayList<TextItem> texts=new ArrayList<>();
 static class TextItem { String value; float x=256,y=420,size=52; String font="SANS"; TextItem(String v){value=v;} }
 public void onCreate(Bundle b){super.onCreate(b);build();}
 TextView title(String s){TextView t=new TextView(this);t.setText(s);t.setTextSize(22);t.setPadding(16,20,16,12);return t;}
 void build(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(16,16,16,16);root.addView(title("Pembuat Stiker WhatsApp"));Button add=new Button(this);add.setText("＋ TAMBAH FOTO");root.addView(add);preview=new ImageView(this);preview.setAdjustViewBounds(true);preview.setScaleType(ImageView.ScaleType.CENTER_INSIDE);root.addView(preview,new LinearLayout.LayoutParams(-1,0,1));Button edit=new Button(this);edit.setText("EDIT STIKER");root.addView(edit);Button wa=new Button(this);wa.setText("SIMPAN KE WHATSAPP");root.addView(wa);setContentView(root);add.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,10);});edit.setOnClickListener(v->{if(selected==null)toast("Pilih foto dulu.");else editDialog();});wa.setOnClickListener(v->{if(selected==null){toast("Pilih foto dulu.");return;}if(edited==null)edited=makeSticker();addToWhatsApp();});}
 void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
 protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==10&&c==RESULT_OK&&d!=null){selected=d.getData();try{getContentResolver().takePersistableUriPermission(selected,d.getFlags()&Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception e){}texts.clear();edited=null;preview.setImageURI(selected);}}
 void editDialog(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(20,0,20,0);EditText e=new EditText(this);e.setHint("Masukkan teks");box.addView(e);Spinner font=new Spinner(this);font.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"SANS","SERIF","MONOSPACE","BOLD","ITALIC"}));box.addView(font);SeekBar size=new SeekBar(this);size.setMax(100);size.setProgress(52);box.addView(size);new AlertDialog.Builder(this).setTitle("Edit stiker").setView(box).setPositiveButton("TAMBAH TEKS",(d,w)->{String s=e.getText().toString();if(!s.isEmpty()){TextItem t=new TextItem(s);t.size=24+size.getProgress();t.font=font.getSelectedItem().toString();texts.add(t);edited=makeSticker();preview.setImageBitmap(edited);}}).setNegativeButton("BATAL",null).show();}
 Bitmap makeSticker(){try{Bitmap src=MediaStore.Images.Media.getBitmap(getContentResolver(),selected);float scale=Math.min(1f,Math.min(512f/src.getWidth(),512f/src.getHeight()));Bitmap b=Bitmap.createScaledBitmap(src,Math.max(1,(int)(src.getWidth()*scale)),Math.max(1,(int)(src.getHeight()*scale)),true);Bitmap out=Bitmap.createBitmap(512,512,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(out);c.drawColor(Color.TRANSPARENT,PorterDuff.Mode.CLEAR);c.drawBitmap(b,(512-b.getWidth())/2f,(512-b.getHeight())/2f,null);for(TextItem t:texts){Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);p.setColor(Color.WHITE);p.setTextSize(t.size);p.setTextAlign(Paint.Align.CENTER);p.setStyle(Paint.Style.FILL);p.setTypeface(t.font.equals("SERIF")?Typeface.SERIF:t.font.equals("MONOSPACE")?Typeface.MONOSPACE:Typeface.DEFAULT);if(t.font.equals("BOLD"))p.setTypeface(Typeface.DEFAULT_BOLD);if(t.font.equals("ITALIC"))p.setTypeface(Typeface.create(Typeface.DEFAULT,Typeface.ITALIC));p.setShadowLayer(8,2,2,Color.BLACK);c.drawText(t.value,t.x,t.y,p);}return out;}catch(Exception e){toast("Gagal memproses foto.");return null;}}
 void addToWhatsApp(){try{File dir=new File(getFilesDir(),"stickers");dir.mkdirs();File[] old=dir.listFiles();if(old!=null)for(File f:old)f.delete();File f=new File(dir,"sticker_1.webp");FileOutputStream os=new FileOutputStream(f);edited.compress(Bitmap.CompressFormat.WEBP,90,os);os.close();Intent i=new Intent("com.whatsapp.intent.action.ENABLE_STICKER_PACK");i.putExtra("sticker_pack_id","khiar_pack");i.putExtra("sticker_pack_authority",StickerProvider.AUTH);startActivity(i);}catch(Exception e){toast("Gagal membuka penambahan paket WhatsApp.");}}
}
